version: '3.8'

services:
  frontend:
    image: sge-front
    container_name: sge-front-container
    build:
      context: frontend
    ports:
      - 5173:5173
    restart: always
    depends_on:
      - backend
    networks:
      - net-front
  backend:
    image: sge-back
    container_name: sge-back-container
    build:
      context: backend
    ports:
      - 3000:3000
    depends_on:
      - db
    restart: always
    networks:
      - net-front
      - net-back
  db:
    image: postgres:13
    container_name: sge-db-container
    environment:
      - POSTGRES_DB=sge_2
      - POSTGRES_USER=alexander
      - POSTGRES_PASSWORD=admin1234
    ports:
      - 5455:5432
    volumes:
     - pgdata:/var/lib/postgresql/data
    networks:
     - net-back

networks:
  net-front:
  net-back:

volumes:
  pgdata: